defaultAssertionDataset: superform_assertion
defaultLocation: EU
defaultProject: dataform-package
vars:
  GA4_DATASET: analytics_31337
  LOCAL_TIMEZONE: Europe/Paris
  QUALITY_DATASET: superform_quality_31337
  TRANSFORMATIONS_DATASET: superform_transformations_31337
  OUTPUTS_DATASET: superform_outputs_31337
  LABEL_GENERIC_BRAND: superformlabs # constant 
  LABEL_GENERIC_TOOL: ga4dataform # constant for now... 
  LABEL_GENERIC_LICENSE_TYPE: core # core or premium 
  LABEL_EXECUTION_OPERATION: daily_workflow # daily_workflow or backfilling 
  LABEL_GENERIC_PACKAGE_VERSION: v1-17-0
  

