defaultLocation: US
defaultProject: pd-strategy
defaultAssertionDataset: gmp_quality
vars:
  OUTPUT_PROJECT: pd-strategy
  GA4_DATASET: analytics_207462216
  LOCAL_TIMEZONE: America/New_York
  QUALITY_DATASET: gmp_quality
  TRANSFORMATIONS_DATASET: gmp_base 
  OUTPUTS_DATASET: gmp_outputs 
  REPORTING_DATASET: gmp_reporting 
  INPUT_PROJECT: infotrust-main-ua-834138-7

